name: Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v3

    - name: Abhängigkeiten installieren
      run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

    - name: Projekt konfigurieren
      run: cmake -S . -B build -G Ninja

    - name: Projekt bauen
      run: cmake --build build

    - name: Tests ausführen
      run: ./build/runTests
